apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/ethanreedt/animal-wiki-taxonomy-explorer-backend:latest@sha256:385239d766afbc506ac04ad091a281f89a23d005944ca575e580df2e73623ed3 # {"$imagepolicy": "flux-system:backend"}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: postgres-db
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
