apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/ethanreedt/animal-wiki-taxonomy-explorer-backend:latest@sha256:4c56a3e457532354620276adf09e3ec9d867b1edeea9205ff9583701c2d8b7e8 # {"$imagepolicy": "flux-system:backend"}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: db-auth
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
