apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/ethanreedt/animal-wiki-taxonomy-explorer-backend:latest@sha256:58ac8b6a77e4a7c16c4d8f97d7a189e34808f44f9dd82499138c2b3aacc3fd09 # {"$imagepolicy": "flux-system:backend"}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: postgres-db
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
