apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../../apps/image-update-automation.yaml
- ../../../apps/frontend
- ../backend # secrets overlay
- ../../../infrastructure/traefik
- ../../../infrastructure/gateway
- ../../../infrastructure/cert-manager
